YahtzeeLight/Models/Database.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace YahtzeeLight.Models
{
    public class Database
    {
        private static List<Speler> spelers = new List<Speler>();

        public static IEnumerable<Speler> Spelers
        {
            get
            {
                return spelers;
            }
        }

        public static int getID()
        {
            return spelers.Count() + 1;
        }

        public static void ClearSpelers() {
            spelers = new List<Speler>();
        }

        public static void VoegSpelerToe(Speler speler)
        {
            spelers.Add(speler);
        }

        public static int TotaalAantalSpelers()
        {
            return spelers.Count();
        }

        public static List<Speler> getSpelersOrderedByScore()
        {
            List<Speler> sortedSpelers = spelers;
            sortedSpelers.Sort((Speler s1, Speler s2) => s1.TotaleScore.CompareTo(s2.TotaleScore));
            sortedSpelers.Reverse();
            return sortedSpelers;
        }

    }
}

YahtzeeLight/Models/Game.cs
using System;
using System.Collections.Generic;
using YahtzeeLight.Infrastructure;

namespace YahtzeeLight.Models
{
    public class Game
    {
        public static void genereerWorpen()
        {
            List<int> worp = new List<int>();
            List<List<int>> worpen = new List<List<int>>();

            foreach (Speler speler in Database.Spelers)
            {
                worpen = new List<List<int>>();
                for (int i = 0; i < 10; i++)
                {
                    worp = new List<int>();
                    for (int j = 0; j < 5; j++)
                    {
                        int dobbel = DiceRandom.random.Next(1, 7);
                        worp.Add(dobbel);
                    }
                    worpen.Add(worp);
                }
                speler.Worpen = worpen;
            }
        }
    }
}

YahtzeeLight/Models/Speler.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using YahtzeeLight.Infrastructure;

namespace YahtzeeLight.Models
{
    public class Speler
    {
        private List<int> _besteWorp;

        public int SpelerID { get; set; }

        public string Naam { get; set; }

        public int TotaleScore { get {
                return berekenTotaleScore();
            }
        } 

        public List<List<int>> Worpen { get; set; }

        public IEnumerable<int> BesteWorp {
            get {
                return sorteerVolgensWaarde(this._besteWorp);
            }
        } 

        private int berekenTotaleScore()
        {
            int score = 0;
            _besteWorp = null;

            foreach (var worp in Worpen)
            {
                int scoreWorp = Combinatie.getScoreFor(worp);
                score += scoreWorp;
                if (_besteWorp == null || scoreWorp > Combinatie.getScoreFor(this._besteWorp))
                {
                    this._besteWorp = worp;
                }
            }

            return score;
        }

        private IEnumerable<int> sorteerVolgensWaarde(List<int> combo)
        {
            List<int> local = combo;

            local.Sort((int a, int b) => a - b);

            return local;
        }
    }
}

YahtzeeLight/Controllers/SpeelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using YahtzeeLight.Models;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace YahtzeeLight.Controllers
{
    public class SpeelController : Controller
    {
        [HttpPost]
        public ViewResult Gegevens(string naam)
        {
            if (string.IsNullOrEmpty(naam)) {
                ViewBag.Error = "Je moet een naam invoeren!";
                return View();
            }

            Speler speler = new Speler()
            {
                Naam = naam,
                SpelerID = Database.getID()
            };

            Database.VoegSpelerToe(speler);

            return View();
        }

        [HttpGet]
        public ViewResult Gegevens()
        {
            return View();
        }

        public ViewResult Uitslag()
        {
            Game.genereerWorpen();

            List<Speler> spelers = Database.getSpelersOrderedByScore();

            ViewBag.spelers = spelers;

            return View();
        }

        public ActionResult NieuweSpelers()
        {
            Database.ClearSpelers();
            return RedirectToAction("Gegevens");
        }

    }
}

YahtzeeLight/Controllers/StartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using YahtzeeLight.Infrastructure;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace YahtzeeLight.Controllers
{
    public class StartController : Controller
    {
        public ViewResult Index()
        {

            DiceRandom.random = new Random();
            return View();
        }

        
    }
}

YahtzeeLight/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Yahtzee Light</title>
    <link href="~/css/style.css" rel="stylesheet" />
</head>
<body>

@RenderBody()

</body>
</html>

YahtzeeLight/Views/Speel/Gegevens.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    string spelernummer = (Database.TotaalAantalSpelers() + 1).ToString();
    bool meerDan1Speler = Database.TotaalAantalSpelers() > 0;
}
<div class="container"> 
    <div class="gegevensContainer">
        <img src="~/img/yahtzee_light_intro.png" />
        <p>Gegevens speler @spelernummer </p>
        <form method="post">
            <p><label for="naam">Naam:</label></p>
            @if (ViewBag.Error != null) {
                <p class="error">@ViewBag.Error</p>
            }
            <p><input type="text" name="naam" id="naam"/></p>
            <p><input type="submit" name="btnSpeler" id="speler" value="Voeg speler toe"></p>
            
            @if (meerDan1Speler) {
            <p><input asp-controller="Speel" asp-action="Uitslag" type="submit" value="Start spel"></p>
            }
        </form>
    </div>
</div>

YahtzeeLight/Views/Speel/ScoreBord.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model YahtzeeLight.Models.Speler
@{
int plaats = (int) ViewData["plaats"];
}
<div class="scoreboard">
    <header> <div>
                @if (plaats == 1) {
                    <img src="~/img/goud.png" />
                } else if (plaats == 2) {
                    <img src="~/img/zilver.png" />
                } else if (plaats == 3) {
                    <img src="~/img/brons.png" />
                } 
        <h1>@Model.Naam </h1> </div> <p>score: @Model.TotaleScore</p>
    </header>

    <div class="score-label-container">
        <div class="label-container">
            <div class="item"> Worp</div>
            <div class="item"> Chance </div>
            <div class="item"> Drie gelijke </div>
            <div class="item"> Vier gelijke </div>
            <div class="item"> Full house </div>
            <div class="item"> Kleine straat </div>
            <div class="item"> Grote straat </div>
            <div class="item"> Yahtzee </div>
        </div>
        
        <div class="score-container">
            
            @for(int i = 1; i <= 10; i++) {
              <div class="item"> @i </div>  
            }

             @foreach(var worp in Model.Worpen){
                <div class="score-grid">
                    <div class="item"> @if(Combinatie.IsChance(worp)){ <div> @Combinatie.getScoreFor(worp) </div>} else {<div>0</div>} </div>
                    <div class="item"> @if(Combinatie.IsDrieGelijke(worp)){ <div> @Combinatie.getScoreFor(worp) </div>} else {<div>0</div>} </div>
                    <div class="item"> @if(Combinatie.IsVierGelijke(worp)){ <div> @Combinatie.getScoreFor(worp) </div>} else {<div>0</div>} </div>
                    <div class="item"> @if(Combinatie.IsFullHouse(worp)){ <div> @Combinatie.getScoreFor(worp) </div>} else {<div>0</div>} </div>
                    <div class="item"> @if(Combinatie.IsKleineStraat(worp)){ <div> @Combinatie.getScoreFor(worp) </div>} else {<div>0</div>} </div>
                    <div class="item"> @if(Combinatie.IsGroteStraat(worp)){ <div> @Combinatie.getScoreFor(worp) </div>} else {<div>0</div>} </div>
                    <div class="item"> @if(Combinatie.IsYahtzee(worp)){ <div class="yahtzee"> @Combinatie.getScoreFor(worp) </div>} else {<div>0</div>} </div>
                </div>
             }
            
        </div>
    </div>
    <footer>
        <p> Beste worp: </p> 
        @foreach(var oog in Model.BesteWorp) {
                <img src="~/img/dice_@(oog).jpg" />
        }
    </footer>
</div>

YahtzeeLight/Views/Speel/Uitslag.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
List<Speler> spelers = (List<Speler>) ViewBag.spelers;
int plaats = 1;
}

<header class="uitslag"> <h1> Uitslag </h1>  <div>
        <input type="button" value="Speel opnieuw" onclick="location.href='@Url.Action("Uitslag", "Speel")'" />
        <input type="button" value="Kies nieuwe spelers" onclick="location.href='@Url.Action("NieuweSpelers", "Speel")'" />
</div></header>

<div class="scoreboard-container" >
    @foreach(var speler in spelers) {
       @await Html.PartialAsync("ScoreBord", speler, new ViewDataDictionary(this.ViewData) { { "plaats", plaats } });
       plaats++;
    }
</div>

YahtzeeLight/Views/Start/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{

}
<div class="container">
    <a asp-controller="Speel" asp-action="Gegevens"><img src="~/img/yahtzee_light_intro.png" /></a>
</div>